# Generated by Django 4.2.7 on 2023-12-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('face_tokens', models.JSONField()),
                ('image_file', models.ImageField(upload_to='faces/')),
            ],
        ),
    ]
